### ISSUE TITLE
Borrow some ideas from django-nonrel/mongodb-cache

### ISSUE THREAD

**Issue by romanukes** [Olivier-OH/django-cache-with-mongodb#4]
Just wanted to discuss a few ideas that could be borrowed from [mongodb-cache](https://github.com/django-nonrel/mongodb-cache):

- Pickle data only if needed like [here](https://github.com/django-nonrel/mongodb-cache/blob/19f28f4ce868462eae9019516cf8d8a6cbb0f7d8/django_mongodb_cache/backend.py#L69-L78)
- Raw data will allow for atomic increment like [here](https://github.com/django-nonrel/mongodb-cache/blob/19f28f4ce868462eae9019516cf8d8a6cbb0f7d8/django_mongodb_cache/backend.py#L82-L100)

Please let me know what you think.

**Comment by Olivier-OH** [comment]
The lib suits my needs, and has suited them for the last couple of years, but if you'd like to make improvements, please go ahead. As long as the base features remain unbroken, I'm pleased that you contribute. :-)

**Comment by kjpc-tech** [comment]
@romanukes have you made in changes to support what you mention above? Particularly raw data instead of pickling when applicable?
